name: Android CI

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Build Type'
        required: true
        default: 'Release'
        options:
          - Release
          - Debug
        type: 'choice'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Decode Keystore
      run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > ./android/app/anime.keystore

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: sudo corepack enable && corepack prepare yarn@3.8.2 --activate && yarn config set -H enableImmutableInstalls false && yarn install

    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assemble${{ inputs.type }}

    - name: Convert Build Type to Lowercase
      run: echo "build_type=$(echo '${{ inputs.type }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-${{ inputs.type }}
        path: android/app/build/outputs/apk/${{ env.build_type }}/anime-arm64-v8a-${{ env.build_type }}.apk
    
    - uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-${{ inputs.type }}
        path: android/app/build/outputs/apk/${{ env.build_type }}/anime-armeabi-v7a-${{ env.build_type }}.apk
 
    - uses: actions/upload-artifact@v4
      with:
        name: x86-${{ inputs.type }}
        path: android/app/build/outputs/apk/${{ env.build_type }}/anime-x86-${{ env.build_type }}.apk
 
    - uses: actions/upload-artifact@v4
      with:
         name: x86_64-${{ inputs.type }}
         path: android/app/build/outputs/apk/${{ env.build_type }}/anime-x86_64-${{ env.build_type }}.apk
 
    - uses: actions/upload-artifact@v4
      with:
         name: universal-${{ inputs.type }}
         path: android/app/build/outputs/apk/${{ env.build_type }}/anime-${{ env.build_type }}-universal.apk